// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using SignInUser.Common.Extensions;
using SignInUser.Models;
using UIKit;

namespace SignInUser
{
    public partial class AccountsViewController : UIViewController
	{
        UITableView table;
        public AccountsViewController (IntPtr handle) : base (handle)
		{
		}

        public AccountsViewController()
        {

        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            btnClose.TouchUpInside += BtnClose_TouchUpInside;
            var scrollView = new UIScrollView(View.Frame);
            table = new UITableView(scrollView.Frame, UITableViewStyle.Plain);
            List<User> users = FileExtensions.GetAccountsFromLocalStorage();
            users = users.OrderBy(x => x.FirstName).ThenBy(x => x.LastName).ToList();
            table.Source = new TableSource(users);
            scrollView.AddSubview(table);
            View.AddSubview(scrollView);
            View.AddSubview(btnClose);
        }

        private void BtnClose_TouchUpInside(object sender, EventArgs e)
        {
            DismissModalViewController(true);
        }
    }
}
